CREATE TABLE [dbo].[tblProduct]
(
	[Product_ID] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
    [Product_Name] VARCHAR(50) NULL, 
    [Product_Image] IMAGE NULL, 
    [Manufacturer_Name] VARCHAR(50) NULL,
    [SubCategory_Name] VARCHAR(50) NULL,
    [Category_Name] VARCHAR(50) NULL,
    [Series] VARCHAR(50) NULL, 
    [Model] VARCHAR(50) NULL, 
    [ModeL_Year] INT NULL, 
    [Type] VARCHAR(50) NULL,
    [Application] VARCHAR(50) NULL, 
    [Mounting_Location] VARCHAR(50) NULL, 
    [Accessories] VARCHAR(50) NULL,
    [Air_Flow] INT NULL,
    [Power_Min] INT NULL, 
    [Power_Max] INT NULL,
    [Operating_Voltage_Min] INT NULL,
    [Operating_Voltage_Max] INT NULL,
    [Fan_Speed_Min] INT NULL, 
    [Fan_Speed_Max] INT NULL,
    [Number_Of_Fan_Speed] INT NULL, 
    [Sound_At_Max_Speed] INT NULL, 
    [Fan_Sweep_Diameter] INT NULL, 
    [Height_Min] INT NULL, 
    [Height_Max] INT NULL, 
    [Weight] INT NULL,
    [Document_Path] VARCHAR(50) NULL
)