<<<<<<< HEAD:JooleWebApplication/Models/tblProjToProd.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjToProd
    {
        public int P2P_ID { get; set; }
        public int Project_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjToProd
    {
        public int P2P_ID { get; set; }
        public int Project_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
>>>>>>> 69a762f6cd11d79ffdbab7181355d8b9a1ba6c36:Joole Application/Models/tblProjToProd.cs
