<<<<<<< HEAD:JooleWebApplication/Models/tblProject.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProject()
        {
            this.tblProjToProds = new HashSet<tblProjToProd>();
        }
    
        public int Project_ID { get; set; }
        public string Project_Name { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Project_Address1 { get; set; }
        public string Project_Address2 { get; set; }
        public string Project_City { get; set; }
        public string Project_State { get; set; }
        public Nullable<int> Project_Postal_Code { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjToProd> tblProjToProds { get; set; }
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProject()
        {
            this.tblProjToProds = new HashSet<tblProjToProd>();
        }
    
        public int Project_ID { get; set; }
        public string Project_Name { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Project_Address1 { get; set; }
        public string Project_Address2 { get; set; }
        public string Project_City { get; set; }
        public string Project_State { get; set; }
        public Nullable<int> Project_Postal_Code { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjToProd> tblProjToProds { get; set; }
    }
}
>>>>>>> 69a762f6cd11d79ffdbab7181355d8b9a1ba6c36:Joole Application/Models/tblProject.cs
